# .gitlab-ci.yml
stages:
  - replicate

variables:
  PYTHON_VERSION: "3.9"
  MAX_WORKERS: "10"

s3_replication:
  stage: replicate
  image: python:${PYTHON_VERSION}
  before_script:
    - python -m pip install --upgrade pip
    - pip install boto3 botocore
  script:
    - echo "Starting S3 replication from ${SOURCE_BUCKET} to ${DEST_BUCKET}"
    - echo "AWS_ACCESS_KEY_ID exists:" $(if [ -n "$AWS_ACCESS_KEY_ID" ]; then echo "YES"; else echo "NO"; fi)
    - echo "AWS_SECRET_ACCESS_KEY exists:" $(if [ -n "$AWS_SECRET_ACCESS_KEY" ]; then echo "YES"; else echo "NO"; fi)
    - echo "SOURCE_BUCKET:" $SOURCE_BUCKET
    - echo "DEST_BUCKET:" $DEST_BUCKET
    - python s3_replication.py | tee s3_replication.log
  artifacts:
    paths:
      - s3_replication.log
    expire_in: 1 month
    when: always
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - when: manual
  timeout: 6h
  retry:
    max: 2
    when:
      - unknown_failure
      - api_failure
      - runner_system_failure
