# .gitlab-ci.yml
variables:
  PYTHON_VERSION: "3.9"
  SOURCE_REGION: "us-west-2"
  DEST_REGION: "us-east-1"
  MAX_WORKERS: "10"

s3_replication:
  image: python:${PYTHON_VERSION}
  before_script:
    - python -m pip install --upgrade pip
    - pip install boto3 botocore
  script:
    - echo "Starting S3 replication from ${SOURCE_BUCKET} to ${DEST_BUCKET}"
    - python s3_replication.py
  artifacts:
    paths:
      - s3_replication.log
    expire_in: 1 month
    when: always
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - when: manual
  timeout: 6h
  retry:
    max: 2
    when:
      - unknown_failure
      - api_failure
      - runner_system_failure
